### ISSUE TITLE
diagnose and fix pink tiles after system upgrade

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#55]
I suspect the upgrade did an OpenGeo Suite upgrade and reset the path to the Geoserver data dir. 

from Andrew:

> I cleaned up the rather full /boot partition and brought the Minisass server up to date with the usual Ubuntu updates earlier this evening. After rebooting the server, I noticed that the map wasn’t working.

The Tomcat7 catalina.out log seems to have an error that matches what’s seen on the website whenever the map is loaded.

05 Aug 00:08:00 ERROR [geoserver.ows] -

org.geoserver.platform.ServiceException: Could not find layer miniSASS:minisass_observations

```
    at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1255)

    at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:221)

    at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:83)

    at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1487)

    at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:675)
```

….<snip>

**Comment by NyakudyaA** [comment]
changed data directory path in web.xml
